### ISSUE TITLE
recreate www directory + introduce user themes

### ISSUE THREAD

**Issue by psyciknz** [linuxserver/docker-tt-rss#15]
If there's a need to recreate the www directory, how can this be done.   A recreate container doesn't seem to trigger it.

2ndly, Is there a way in pulling the image, that a user theme can be loaded?  ie the feedly one?

**Comment by thelamer** [comment]
Under the current logic you would need to wipe your config data (you can backup your config.php) and recreate the container. 
As for installing themes see here: 
https://git.tt-rss.org/fox/tt-rss/wiki/Themes
That would be /config/www/tt-rss/themes.local under the current logic. 

Just a heads up we are pending some pretty major changes to this container if you want to follow here: 
https://github.com/linuxserver/docker-tt-rss/pull/24

This would shift your theme directory to /config/themes.local and be persistent between upgrades of the container.
