### ISSUE TITLE
Download TT-RSS at image build time

### ISSUE THREAD

**Issue by Neraud** [linuxserver/docker-tt-rss#16]
Currently, TT-RSS is downloaded when the container is first started using [40-install](https://github.com/linuxserver/docker-tt-rss/blob/master/root/etc/cont-init.d/40-install)

So even if I lock the docker image version, depending on when I start the container I might end up with a different version of TT-RSS running.

Looking at other linuxserver repos, other PHP applications like [docker-bookstack](https://github.com/linuxserver/docker-bookstack/) download the application at image build time.

I'm assuming changing this will not be trivial as TT-RSS is currently downloaded in the /config volume.

**Comment by kelvinhammond** [comment]
TT-RSS doesn't even get updated with the current image, once its downloaded it never updates tt-rss.

**Comment by Neraud** [comment]
Yes, while the container (or rather the volume) is there, it's never updated.

Now, let's say I test on *host_staging* `linuxserver/tt-rss:153`.
After a week, I'm fine with it, and want to deploy it on *host_prod*.
While I use the exact same image, a different version of TT-RSS will be downloaded there.

A more reaslistic use case, what happens if I want to run an older version of TT-RSS because the last one broke my custom theme/plugin ? I would simply want to pin the image version.

**Comment by Fmstrat** [comment]
Unfortunately running across this is the exact reason I can't use this image. Every other Linuxserver container I uses updates the software based on the build. This one doesn't.

**Comment by Fmstrat** [comment]
After some further investigation, I've come to the conclusion that TT-RSS is just designed in a way that makes this difficult. Their upgrade path is a `git pull`, and they have all kinds of craziness in the `.gitignore` to make this work: https://git.tt-rss.org/fox/tt-rss/src/master/.gitignore

Why they didn't use a data directory for all dynamic content we'll probably never know. I'm tempted to join the Discourse to ask, but instead will probably spend some time forking this and seeing if I can make an update at build work.

**Comment by Fmstrat** [comment]
I started a convo about data folders here: https://discourse.tt-rss.org/t/overhaul-ttrss-needs-a-data-directory/1922

In the meantime, I also supplied a PR to make updating at least possible.

**Comment by Fmstrat** [comment]
@Neraud @kelvinhammond While I made the PR above, I think the Linuxserver team should change their methodology to match the version of tt-rss I just created: https://hub.docker.com/r/nowsci/docker-ttrss

It creates the tt-rss image at build time, and puts only files that are unique to a users installation in the data volume. It also includes all prerequisites for plugins, LDAP, all DB types, and international support.

Give it a shot if you would like.

**Comment by Neraud** [comment]
I also made a PR after opening 2 issues (https://github.com/linuxserver/docker-tt-rss/pull/18)

**Comment by 0x9394** [comment]
always failed with download process.

put the link in browser download works. (https://git.tt-rss.org/git/tt-rss/archive/19.2.tar.gz, with notice: Checking your browser before accessing tt-rss.org. ..... DDoS protection by Cloudflare  ...), 

<pre>
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
...............................................................+++++
.......................................+++++
writing new private key to '/config/keys/cert.key'
-----
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-install: executing... 
fetching tt-rss files, this may take a little while
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8429    0  8429    0     0   7083      0 --:--:--  0:00:01 --:--:--  7083
gzip: invalid magic
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[cont-init.d] 40-install: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.


$ sudo docker exec -it tt-rss /bin/bash
root@5a98ea79f098:/$ cat /version.txt 
19.2
root@5a98ea79f098:/$ curl -o /tmp/tt-rss.tar.gz -L https://git.tt-rss.org/git/tt-rss/archive/19.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5760    0  5760    0     0   5944      0 --:--:-- --:--:-- --:--:--  5938
root@5a98ea79f098:/$ ls /tmp
tt-rss.tar.gz
root@5a98ea79f098:/$ ls /tmp -lh
total 8.0K
</pre>

**Comment by thelamer** [comment]
@kt1024 It has to be Geo based or some kind of blocking on VPN providers I tested it from US, Canada, and Mexico and I am not getting this.

**Comment by 0x9394** [comment]
@thelamer 
from P.R China, always get the 'scan' message with cloudflare hosted sites.  I'm waiting for the git version above mentioned.

**Comment by thelamer** [comment]
Please reference this PR for updates: 
https://github.com/linuxserver/docker-tt-rss/pull/24
