### ISSUE TITLE
Feeds not updating, S6 update_daemon2.php file not at linked location

### ISSUE THREAD

**Issue by Mist-Hunter** [linuxserver/docker-tt-rss#25]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

**Armhf, Raspbian 9 (Stretch) on Raspberry Pi 3 B+**

sudo bash
mkdir /home/pi/tt-rss
chown -R pi /home/pi/tt-rss
docker run \
-d \
--name=tt-rss \
-e PUID=1000 \
-e PGID=1000 \
-e TZ=America/Los_Angeles \
-e DB_TYPE=pgsql \
-e DB_HOST=rss.lan \
-e DB_USER=ttrss \
-e DB_NAME=ttrss \
-e DB_PASS='<REMOVED>' \
-e DB_PORT=5432 \
-e SELF_URL_PATH=http://rss.lan \
-p 80:80 \
-p 443:443 \
-v /home/pi/tt-rss:/config \
--restart unless-stopped \
linuxserver/tt-rss

      

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 10-adduser: executing... 

-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \ 

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/

Brought to you by linuxserver.io

We gratefully accept donations at:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------

User uid:    1000

User gid:    1000

-------------------------------------

[cont-init.d] 10-adduser: exited 0.

[cont-init.d] 19-newdefault: executing... 

[cont-init.d] 19-newdefault: exited 0.

[cont-init.d] 20-config: executing... 

[cont-init.d] 20-config: exited 0.

[cont-init.d] 30-config: executing... 

DB_TYPE set, injecting env variables into config.php

Creating config.php from the dist file

[cont-init.d] 30-config: exited 0.

[cont-init.d] 30-keygen: executing... 

generating self-signed keys in /config/keys, you can replace these with your own keys if required

Generating a RSA private key

..........................................+++++

........+++++

writing new private key to '/config/keys/cert.key'

-----

[cont-init.d] 30-keygen: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

nano /run/s6/services/update-feeds/run #shows
#!/usr/bin/with-contenv bash

        s6-setuidgid abc php7 \
        /config/www/tt-rss/update_daemon2.php > /dev/null 2>&1

/config/www$ ls
index.html

(missing tt-rss directory at referenced location)

Thank you for the container, I hope I'm not missing something on my end.

**Comment by thelamer** [comment]
@Mist-Hunter no you are 100% correct we missed this in our conversion to installing the application inside the container, https://github.com/linuxserver/docker-tt-rss/pull/26 should resolve this, pending a merge

**Comment by thelamer** [comment]
Can you update your container and let us know if this is still an issue @Mist-Hunter : 
```
sudo docker run --rm \
-v /var/run/docker.sock:/var/run/docker.sock taisun/updater \
--oneshot tt-rss
```

**Comment by Mist-Hunter** [comment]
I rebuilt with my original posted command, and can verify it is now updating. I imported my OPML and watched it update over 100 feeds. Thanks for the quick fix!

`sudo bash
mkdir /home/pi/tt-rss
chown -R pi /home/pi/tt-rss
docker run \
-d \
--name=tt-rss \
-e PUID=1000 \
-e PGID=1000 \
-e TZ=America/Los_Angeles \
-e DB_TYPE=pgsql \
-e DB_HOST=rss.lan \
-e DB_USER=ttrss \
-e DB_NAME=ttrss \
-e DB_PASS='' \
-e DB_PORT=5432 \
-e SELF_URL_PATH=http://rss.lan \
-p 80:80 \
-p 443:443 \
-v /home/pi/tt-rss:/config \
--restart unless-stopped \
linuxserver/tt-rss`

**Comment by thelamer** [comment]
@Mist-Hunter No problem I was the one that broke it ;)
