### ISSUE TITLE
With in container install , config not persistent with fresh pull on existing data.... 

### ISSUE THREAD

**Issue by sparklyballs** [linuxserver/docker-tt-rss#27]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

+ switched to the new style with in container app and new /config mount etc.
+ tested with pulling a new container and applying over existing data (existing data, being the "new" /config from previous step here)
+ no config preserved and back to setup screen...

**Comment by sparklyballs** [comment]
sparklyballs@proxmox:~/appdata/tt-rss$ docker exec -it tt-rss bash
root@245a3843276f:/$ find / -iname "config.php"
root@245a3843276f:/$ find / -iname "*config.*php*"
/var/www/html/lib/phpqrcode/tools/merged_config.php
/var/www/html/lib/phpqrcode/qrconfig.php
/var/www/html/config.php-dist
/var/www/html/include/sanity_config.php

**Comment by sparklyballs** [comment]
https://github.com/linuxserver/docker-tt-rss/blob/master/root/etc/cont-init.d/30-config#L9

never gonna be internal to the container on first run....

side note, WAY too many sed's for settings etc....

**Comment by sparklyballs** [comment]
subsequent runs (after exec'ing into the container and manually adding the config file by editing the .dist version with correct values) results in a persistent config file in /config after a restart.

but for first time users, this won't survive any image update they attempt..

**Comment by sparklyballs** [comment]
update:-

if i pull a new image, i get the setup screen yet again. 

basically it seems unless you use the "advanced" setting of injecting the variables , the config doesn't exist in the image, despite the file existing in the /config mount.

**Comment by thelamer** [comment]
Yeah we specifically go over this in the application setup section of the readme .

**Comment by sparklyballs** [comment]
that's ok for an existing container...

BUT if you pull a new image, which i did to simulate an update, the config doesn't exist anymore at /var/www/html/ and gives me the setup screen again.

the only remedy is to exec in and copy it manually from /config to the intended location.

**Comment by thelamer** [comment]
If the file exists in the config directory the in container variant is purged and a symlink replaces it. That logic is here https://github.com/linuxserver/docker-tt-rss/blob/master/root/etc/cont-init.d/30-config#L18

**Comment by sparklyballs** [comment]
needs logic for an existing config file in /config... on a repull (i.e update),

**Comment by sparklyballs** [comment]
needs logic for an existing config file in /config... on a repull (i.e update),

**Comment by sparklyballs** [comment]
the file DOESN'T exist in the image.... and never will on a fresh pull.

**Comment by sparklyballs** [comment]
what i have done from the beginning.

saved out my OPML file
cleared all existing appdata from old style and made a new user and database in mariadb. ie clean slate approach.

setup image... 

simulated an update and got the update screen...

manually entered the required config in the container..

it survives a restart....

but pulling again results in the setup screen again....

someone will inevitably end up adding details again and will get problems.... 

it's not right, shouldn't have to restart container twice after every update....

**Comment by thelamer** [comment]
Yeah the process is:
Spinup and run setup
Restart container 

This is covered in the readme .

**Comment by sparklyballs** [comment]
you're missing the salient point here....


if you run the setup , it survives restarts...

BUT if you update the image with the file in /config, it dumps you back at setup....

**Comment by sparklyballs** [comment]
and you can't enter setup details twice, to the best of my knowledge as it tries to initialise the database  
which has already happened

**Comment by thelamer** [comment]
Ahh I see your point the guard has the clause for the file also existing in the container which it does not by default, will get that fixed right away.

**Comment by thelamer** [comment]
Pending merge of #28
