### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by JOduMonT** [linuxserver/docker-tt-rss#29]
on a new install I had to 

mkdir /config/{cache/{images,upload,export},feed-icons,lock}
chmod 0777 -R /config/{cache,feed-icons,lock}

to make it work
```

Startup failed

Tiny Tiny RSS was unable to start properly. This usually means a misconfiguration or an incomplete upgrade. Please fix errors indicated by the following messages:
Image cache is not writable (chmod -R 777 cache/images)
Upload cache is not writable (chmod -R 777 cache/upload)
Data export cache is not writable (chmod -R 777 cache/export)
ICONS_DIR defined in config.php is not writable (chmod -R 777 feed-icons).
LOCK_DIRECTORY defined in config.php is not writable (chmod -R 777 lock).

You might want to check tt-rss wiki or the forums for more information. Please search the forums before creating new topic for your question.
```

**Comment by thelamer** [comment]
I am at about 99% confidence you are not using the correct pgid and puid settings for your container . 

Regardless in the future try testing out containers without the external volumes set before filing a bug report here. 

If you need further assistance please hop on our discord as it makes support much easier . https://discord.gg/YWrKVTn

**Comment by JOduMonT** [comment]
_all other ls container don't have any issue on the same host but if you say so ;)_

@thelamer discord is not opensource;
so against my religion :P
just kidding !!!

I'll try to visit discord more often
