### ISSUE TITLE
ssl port map not work

### ISSUE THREAD

**Issue by 0x9394** [linuxserver/docker-tt-rss#31]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

currently cert file is generated, but config.php & nginx conf is not ready for ssl.
br.

**Comment by thelamer** [comment]
This is by design, we leave the nginx config in the config directory to allow users to customize to their needs. 

The cert generation is part of the base image logic and we run it on all of our nginx containers.
