### ISSUE TITLE
Can not set booleans using env variables

### ISSUE THREAD

**Issue by vfauth** [linuxserver/docker-tt-rss#33]
With version 19.2-ls11.

I set all the variables I need in config.php by using environment variables in docker run.

I tried to set SINGLE_USER_MODE=false. However, in the config.php file generated from the environment variables, I have `define('SIMPLE_UPDATE_MODE', 'false');` instead of `define('SIMPLE_UPDATE_MODE', false);` (note the quotes). This is interpreted as `true`.

**Comment by thelamer** [comment]
Yeah I see what you mean, will have a PR shortly when I can review all the potential Boolean values in the config.
