### ISSUE TITLE
PDO error using pgsql driver

### ISSUE THREAD

**Issue by Chaz6** [linuxserver/docker-tt-rss#35]
When running the container with the pgsql driver the server reports `Exception while creating PDO object:SQLSTATE[08006] [7] invalid port number: "tcp://172.17.0.4:5432"`

This is the command line:-
```
docker create \
  --name=tt-rss \
  -e PUID=1000 \
  -e PGID=1000 \
  -e DB_TYPE=pgsql \
  -e DB_NAME=user \
  -e DB_USER=pass \
  -e DB_PASS=database \
  -e SELF_URL_PATH=https://www.example.com/ttrss/ \
  -e TZ=Europe/London \
  -p 127.0.0.1:8081:80 \
  --link tinydatabase:db \
  -v /home/chaz/docker/tt-rss/config:/config:Z \
  --restart unless-stopped \
  linuxserver/tt-rss
```

I am sorry I do not know what the solution is.

**Comment by j0nnymoe** [comment]
You've missed out `DB_HOST` and `DB_PORT`.

**Comment by Chaz6** [comment]
Thank you for the response. I thought it would be inherited from the database container when using docker --link, and the error message suggested that something was supplied as a port number ("tcp://172.17.0.4:5432") which is why I thought it was an issue.
