### ISSUE TITLE
Installation of TT-RSS into a subfolder at the www root

### ISSUE THREAD

**Issue by ryester19** [linuxserver/docker-tt-rss#36]
While working on creating a subfolder config for the linuxserver/letsencrypt Docker image, I have come to the conclusion that reverse proxying can't fully work unless TT-RSS is also being served from a subfolder. TT-RSS doesn't have a "Base URL" setting, and the SELF_URL_PATH config option doesn't act as a substitute. URI rewriting at the proxy side only goes so far.

The proposed idea is to create a new Docker environmental variable that would let you set the name of the subfolder that TT-RSS will be installed into, rather than directly into /var/www/html. If the variable is omitted, TT-RSS will install into the www root, like before.

**Comment by thelamer** [comment]
If you are just trying to change the path you can use the nginx config to set a different path in your `/config/nginx/site-confs/default` file. 

under the ```	location / {``` directive. 

But you also need to ensure the app is aware of its location. Take a look at this thread for more info: 
https://discourse.tt-rss.org/t/tt-rss-installation-behind-nginx-reverse-proxy/850

**Comment by ryester19** [comment]
If I move TT-RSS myself from /var/www/html to /var/www/html/ttrss, won't rebuilding the container continue to extract everything into /var/www/html according to the Dockerfile?

**Comment by thelamer** [comment]
You gotta slowly read my response. You do not need to move files to serve them as a subfolder, it is literally all I talked about in my response.

**Comment by ryester19** [comment]
So I think I finally figured this out. The "File Not Found" error I was getting before I made any changes to the container nginx config was related to FastCGI. All I needed to do was change the REQUEST_URI parameter and insert it after the part where you include the fastcgi_params file

`fastcgi_param REQUEST_URI '/tt-rss$request_uri';`

For the sake of simplicity for other users wanting to use my nginx reverse proxy config, is to possible to set this FastCGI parameter at the reverse proxy side and have it be inherited by the container nginx instance?

**Comment by CHBMB** [comment]
@ryester27 Can you provide some more detailed instructions on the steps you had to take and exactly what files you had to edit?  

I don't think we can give you an answer to your question at the moment until we can see exactly what needs to be done.

**Comment by ryester19** [comment]
Sure. Over in the proxy-confs folder of a linuxserver/letsencrypt container, I have this config:
```
location /tt-rss {
    return 301 $scheme://$host/tt-rss/;
}

location ^~ /tt-rss/ {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /login;

    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_ttrss tt-rss;
    rewrite /tt-rss(.*) $1 break;
    proxy_pass http://$upstream_ttrss:80;

    proxy_set_header Host $host;
    proxy_set_header X-FORWARDED-PROTO https;
}

location ^~ /tt-rss/api {
    include /config/nginx/proxy.conf;
    resolver 127.0.0.11 valid=30s;
    set $upstream_ttrss tt-rss;
    rewrite /tt-rss(.*) $1 break;
    proxy_pass http://$upstream_ttrss:80;

    proxy_set_header Host $host;
    proxy_set_header X-FORWARDED-PROTO https;
}
```

and over at the default nginx site config in the linuxserver/tt-rss container, I only needed to add a fastcgi_param directive at the end of the location ~ \.php$ block:

```
server {
        listen 80 default_server;
        root /var/www/html;
        index index.html index.htm index.php;

        server_name _;

#       ssl_certificate /config/keys/cert.crt;
#       ssl_certificate_key /config/keys/cert.key;

        client_max_body_size 0;

        location / {
                try_files $uri $uri/ /index.html /index.php?$args =404;
        }

        location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
                include /etc/nginx/fastcgi_params;
                fastcgi_param REQUEST_URI '/tt-rss$request_uri';
        }
}
```
Everything appears to be working, and I plan to submit a PR to the linuxserver/reverse-proxy-confs repo soon. Before I do I wanted to see if there was anything that can be changed so that people wanting to use the reverse proxy config don't have to touch the nginx config of the tt-rss container at all.
