### ISSUE TITLE
Lock Stamp file does not exist

### ISSUE THREAD

**Issue by monik3r** [linuxserver/docker-tt-rss#37]
Just installed from dockerhub, verified that I'm using the correct UID and GID for writing files (the lock itself seems to have no problem writing). I've set up the db and everything, but when trying to load feeds I get the following in the error log:

`file_get_contents(lock/update_daemon.stamp): failed to open stream: No such file or directory`

I've tried deleting the lock file that is present, update_daemon.lock, creating the file manually, and setting permissions to 0777, however the error keeps coming up The docker logs are unhelpful, there isn't anything about any error, just a normal install and startup. Any ideas would be appreciated, thanks!

**Comment by sparklyballs** [comment]
what host os , docker run command,  etc... ?

the stuff in the template you see when you post an issue, we ask for it, because it's the first port of call for any problems, and can more often than not provide an answer.

**Comment by monik3r** [comment]
Fixed, sorry for the inconvenience. Storing data over nfs works so long as you don't allow for the locks to be placed over nfs (they don't work over nfs). Changing the command from 

`docker create --name=tt-rss -e PUID=1000 -e PGID=1004 -e TZ=America/New_York -p 80:80 -v /mnt/nfs/rss:/config --restart unless-stopped linuxserver/tt-rss`

to 

`docker create --name=tt-rss -e PUID=1000 -e PGID=1004 -e TZ=America/New_York -p 80:80 -v /mnt/nfs/rss:/config -v /home/homelab/rss:/config/lock --restart unless-stopped linuxserver/tt-rss`

Fixed the issue and now tinyrss works
