### ISSUE TITLE
Latest builds seems to break ARM support (Raspberry Pi 3 B+)

### ISSUE THREAD

**Issue by Mist-Hunter** [linuxserver/docker-tt-rss#40]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
Thanks for the work on this container, I use it all the time an appreciate your work!

Latest builds seems to break ARM support (Raspberry Pi 3 B+)

Roll back to 19.2-ls21 resolves the issue.

Raspbian Stretch

Log output:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
-------------------------------------
_         ()
| |  ___   _    __
| | / __| | |  /  \ 
| | \__ \ | | | () |
|_| |___/ |_|  \__/
Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 19-newdefault: executing... 
[cont-init.d] 19-newdefault: exited 0.
[cont-init.d] 20-config: executing... 
/var/run/s6/etc/cont-init.d/20-config: line 15: /usr/bin/find: cannot execute binary file: Exec format error
/var/run/s6/etc/cont-init.d/20-config: line 24: /bin/sed: cannot execute binary file: Exec format error
/var/run/s6/etc/cont-init.d/20-config: line 26: /bin/sed: cannot execute binary file: Exec format error
/var/run/s6/etc/cont-init.d/20-config: line 27: /bin/sed: cannot execute binary file: Exec format error
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-config: executing...

**Comment by sparklyballs** [comment]
https://pastebin.com/EtGjZJ0x

no issues here....

**Comment by thelamer** [comment]
Raspbian is weird because they compile everything for armv6 to support pi zero and the model 1. 
Did you install docker from here? 
```
sudo add-apt-repository \
   "deb [arch=armhf] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"
```

https://docs.docker.com/install/linux/docker-ce/debian/

**Comment by Mist-Hunter** [comment]
Thanks for the quick reply, linuxserver/tt-rss:arm32v7-latest and linuxserver/tt-rss:latest are both still giving me that "cannot execute binary file: Exec format error" maybe I've go something going on in my local environment. I'll try on a fresh install of straight Rasbian, currently on DietPi (modified Rasbian).
