### ISSUE TITLE
Can the 'latest' tag track master?

### ISSUE THREAD

**Issue by wbagdon** [linuxserver/docker-tt-rss#41]
tt-rss maintainer notes that tt-rss is a rolling release model based on the master branch:
https://discourse.tt-rss.org/t/version-bump-for-ttrss/2655/2

Can the 'latest' tag of this docker image be made to follow the master branch of tt-rss?

**Comment by thelamer** [comment]
Can you test the `linuxserver/tt-rss:develop` tag and verify all functionality?

**Comment by wbagdon** [comment]
Looks good, thanks!

**Comment by thelamer** [comment]
More than a spot check, please put this though it's paces and report back in 24 hours. Then we can advertise the tag on dockerhub .

**Comment by wbagdon** [comment]
OK understood, I've been using my own builds of this against master for about a month.
I'll go outside of my normal routine to test out everything though.

**Comment by aptalca** [comment]
`latest` on docker hub is the default tag. If you try to pull an image without a tag, you automatically get `latest` so we make sure that it points to stable releases

EDIT: yeah I don't know why I responded to the title when there's already been message chain, lol. Trying to multi task and failing at it. Anyway, I think the comment is still relevant. Having latest tracking stable releases and develop tracking master branch commits is ideal.

**Comment by wbagdon** [comment]
`master` is considered stable by the maintainer of tt-rss
Edit (additional source): https://git.tt-rss.org/fox/tt-rss/wiki/Home#download

**Comment by aptalca** [comment]
Then what's the point of versioned releases? https://git.tt-rss.org/fox/tt-rss/releases

Makes no sense

**Comment by wbagdon** [comment]
The versioned release has never meant anything:
https://discourse.tt-rss.org/t/is-v15-7-the-latest/278/2

AFAIK the version is only used as a sort of check against themes, but he just did a large CSS overhaul and then didn't update the version so it's 100% useless...

Agreed that it makes no sense but ¯\_(ツ)_/¯

**Comment by wbagdon** [comment]
Everything looks good after a few more days of usage.

**Comment by partymike** [comment]
I've tried the tags :latest & :develop which both seem to be outdated compared to the released @ https://git.tt-rss.org/git/tt-rss/src/master - looking above are you saying to use :master for the latest builds? I've been trying to get some plugins working but due to the age of :latest (2yrs?) they are not working....although I'm unsure if the version number shown of 17.4 in preferences has just never been updated by fox?

**Comment by wbagdon** [comment]
@partymike `latest` should still be tracking tagged releases and should display 19.2 in the settings page. `develop` is tracking the `master` branch but will also display 19.2 due to the way fox detects the version.
You may want to make sure you are running a `docker pull` as it sounds like you're stuck on an old image of you're seeing 17.4 in your version

**Comment by partymike** [comment]
well, the :develop tag never existed on my system before...but I deleted all the volumes and then recreated (compose) and I still see 17.4 at the bottom of the pref screen - is there anywhere else I should look? TBH everything works bar this 1 plugin where the author seem to confirm that was due to the tt-rss version I had being out of date.

scratching my head at this one!

**Comment by aptalca** [comment]
Just created a new container with the develop tag and the bottom shows 19.2

**Comment by partymike** [comment]
Here is my compose file, guessing best way forward would be to backup then nuke tt-rss config folder and start again?

`# tt-rss
  tt-rss:
    image: linuxserver/tt-rss:develop
    container_name: tt-rss
    restart: always
    volumes:
      - /home/admin/.docker/ttrss:/config
    ports:
      - "8085:80"
    environment:
      - TZ=Europe/London
      - PGID=101
      - PUID=1024
    depends_on:
      - data-postgres

# postgres
  data-postgres:
    image: postgres
    container_name: data-postgres
    restart: always
    volumes:
      - /home/admin/.docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=xxxx`

**Comment by thelamer** [comment]
Yeah, we specifically do not update or mess with legacy installs that have the data in /config , you need to essentially start over if you want to upgrade. https://github.com/linuxserver/docker-tt-rss/blob/master/root/etc/cont-init.d/30-config#L3
This container now symlinks out all data and does not install to persistent storage in the modern version so it is 100% docker to upgrade.
