### ISSUE TITLE
latest version of tt-rss

### ISSUE THREAD

**Issue by partymike** [linuxserver/docker-tt-rss#43]
I've tried the tags :latest & :develop which both seem to be outdated compared to the releases @ https://git.tt-rss.org/git/tt-rss/src/master - looking at closed support jobs here there is an indication to use :master for the latest builds? I've been trying to get some plugins working but due to the age of :latest (2yrs?) they are not working....although I'm unsure if the version number shown in tt-rss/preferences of 17.4 has just never been updated by fox?

Hard to move past the current version of tt-rss in this docker while troubleshooting the problem.

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-tt-rss/issues/41#issuecomment-520447769
