### ISSUE TITLE
Typo in the README file - 'gaurd'

### ISSUE THREAD

**Issue by lgp171188** [linuxserver/docker-tt-rss#47]
There is a typo in the `README.md` file in the following quoted paragraph (emphasis mine) where `guard` is misspelled as `gaurd`.

> The container can configure itself using environment variables, the **gaurd** for this logic to run is if the variable DB_TYPE is set. The most common variables to set are a URL for the application and a database endpoint. IE:

**Comment by ironicbadger** [comment]
Looks done to me.
