### ISSUE TITLE
alpine base breaks cache_starred_images plugin

### ISSUE THREAD

**Issue by 7twin** [linuxserver/docker-tt-rss#48]
## Current Behavior
Due to the image being based on alpine ([1](https://github.com/linuxserver/docker-tt-rss/blob/master/Dockerfile#L1), [2](https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/master/Dockerfile#L1)) it causes the same warnings/issues as people running tt-rss on alpine: https://community.tt-rss.org/t/php-7-3-use-of-undefined-constant-glob-brace/2230/4

Going to tt-rss logs you can see all the same warnings getting spammed very quickly:
```
E_WARNING (2) | plugins/cache_starred_images/init.php:82 | Invalid argument supplied for foreach()
E_WARNING (2) | plugins/cache_starred_images/init.php:77 | glob() expects parameter 2 to be int, string given
E_WARNING (2) | plugins/cache_starred_images/init.php:77 | Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' (this will throw an Error in a future version of PHP)
```

**Comment by aptalca** [comment]
This image has been deprecated
