### ISSUE TITLE
installation/configuration is very confusing

### ISSUE THREAD

**Issue by JOduMonT** [linuxserver/docker-tt-rss#50]
Hi;

## How to reproduce

This is how I spin it as user which have UID:1000 and GID: 1000
_so it's not an write permission issue_

```
docker create \
  --name=tt-rss \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -p 80:80 \
  -v ./data/tt-rss:/config \
  --restart unless-stopped \
  linuxserver/tt-rss
```

## NGINX SITE-CONFS ?

**I beleive the issue is:**
The nginx site-confs point to `/var/www/html` not to `/config/www`

```
cat data/tt-rss/nginx/site-confs/default 
server {
        listen 80 default_server;
        root /var/www/html;
```

```
ls data/tt-rss/www/
index.html
```

```
docker exec tt-rss ls /var/www/html/
CONTRIBUTING.md
COPYING
README.md
api
atom-to-html.xsl
backend.php
cache
classes
config.php
config.php-dist
css
errors.php
feed-icons
images
include
index.php
install
js
lib
locale
lock
messages.pot
opml.php
plugins
plugins.local
prefs.php
public.php
register.php
schema
templates
tests
themes
themes.local
update.php
update_daemon2.php
utils
vendor
```

**Comment by JOduMonT** [comment]
probably related to
- https://github.com/linuxserver/docker-tt-rss/blob/master/root/defaults/default.incontainer#L3
versus
- https://github.com/linuxserver/docker-tt-rss/blob/master/root/defaults/default#L3

**Comment by JOduMonT** [comment]
I also have this line in my log: `tt-rss         | ln: failed to create symbolic link '/var/www/html/config.php': File exists`

**Comment by JOduMonT** [comment]
Ok I think I understand why it's like that, 

but you should really think in a way to access `config.php`
because it the **Power users** way seams to not populate the database automaticaly or I don't know what but when I tried I had an `error 500` instead of a tt-rss welcome page, while when I comment the environment variable and cut and paste it through the installer it's working well.

https://github.com/linuxserver/docker-tt-rss/issues/32

**Comment by JOduMonT** [comment]
Nevermind; I restart the container and now config.php is in `localhost:.config/`
but I had an error telling me `SELF_URL_PATH=` as to be https and not http while [here](https://github.com/linuxserver/reverse-proxy-confs/blob/master/tt-rss.subdomain.conf.sample#L2) you recommend http and not https

**Comment by aptalca** [comment]
This image has been deprecated
