### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by qokelate** [linuxserver/docker-tt-rss#51]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

On subcride: https://blog.hackpascal.net/feed/
Couldn't download the specified URL: ; 60 SSL certificate problem: unable to get local issuer certificate

docker  run   'linuxserver/tt-rss:cd4b7f19-ls19'
docker exec bash

```
xxxxxxx@xxxxxxxx:/tmp# curl 'https://blog.hackpascal.net/feed/'
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by aptalca** [comment]
This image has been deprecated
