### ISSUE TITLE
Versioning changes in tt-rss

### ISSUE THREAD

**Issue by wbagdon** [linuxserver/docker-tt-rss#52]
https://community.tt-rss.org/t/versioning-changes-for-trunk/2974

Please update logic to make what is currently `develop` to `latest`

**Comment by aptalca** [comment]
Nice little rant there by the dev

**Comment by wbagdon** [comment]
Hostile 😬

**Comment by aptalca** [comment]
Sorry you had to be the target of the attacks.

We're discussing internally how to move forward with tt-rss. After all, we all do this in our spare time, for fun. It's no fun to deal with an upstream dev who acts like that.

**Comment by wbagdon** [comment]
OK sounds good, I'll continue to watch to see what you come up with.
Not the first time I've had to deal with the dev's attitude, so I'm looking at alternatives anyway.

Miniflux might meet mine/others needs:
https://github.com/miniflux/miniflux

**Comment by aptalca** [comment]
This image has been deprecated
